name: sponsors
on:
  workflow_dispatch:

jobs:
  update-sponsors:
    ## Only run on the upstream repository.
    if: github.repository == 'fedify-dev/fedify'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
        persist-credentials: true
        fetch-depth: 0
    - uses: denoland/setup-deno@v1
      with:
        deno-version: 2.4.5  # Keep in sync with mise.toml
    - uses: qoomon/actions--setup-git@v1
    - run: |
        set -e
        deno run \
          --allow-net=opencollective.com \
          --allow-read=README.md,SPONSORS.md \
          --allow-write=README.md,SPONSORS.md \
          scripts/sponsors.ts \
          README.md \
          SPONSORS.md
        cat SPONSORS.md
        if ! git diff-index --quiet HEAD --; then
          git add README.md SPONSORS.md
          git commit -m "Update sponsors" || true
        fi
    - uses: ad-m/github-push-action@master
      with:
        ssh: true
        branch: main

# cSpell: ignore qoomon opencollective
